name: PoetryGame
version: 1.3-SNAPSHOT
api-version: 1.13
main: net.pvpin.poetrygame.api.Main
author: William_Shi
commands:
  flutteringblossoms:
    aliases: [ "fb" ]
  poetrywordle:
    aliases: [ "pw" ]
  poetryidentification:
    aliases: [ "pi" ]
  poetryfilling:
    aliases: [ "pf" ]